version: '3'

services:
  broker-service:
    image: mrfranco/broker-service:1.0.1
    deploy:
      mode: replicated
      replicas: 1

  listener-service:
    image: mrfranco/listener-service:1.0.0
    deploy:
      mode: replicated
      replicas: 1

  authentication-service:
    image: mrfranco/authentication-service:1.0.0
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DATABASE_DSN: "host=postgres port=5432 user=postgres password=password dbname=users sslmode=disable timezone=UTC connect_timeout=5"
      
  logger-service:
    image: mrfranco/logger-service:1.0.1
    deploy:
      mode: replicated
      replicas: 1

  mailer-service:
    image: mrfranco/mailer-service:1.0.0
    deploy:
      mode: replicated
      replicas: 1
    environment:
      MAIL_DOMAIN: localhost
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
      MAIL_USERNAME: ""
      MAIL_PASSWORD: ""
      MAIL_ENCRYPTION: none
      FROM_NAME: "Marcelo"
      FROM_ADDRESS: "marcelo@example.com"

  rabbitmq:
    image: 'rabbitmq:3.11.9-alpine'
    deploy:
      mode: global

  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - "8025:8025"
    deploy:
      mode: global

  mongo:
    image: 'mongo:latest'
    ports:
      - "27017:27017"
    deploy:
      mode: global
    environment:
      MONGO_INITDB_DATABASE: logs
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./db-data/mongo/:/data/db

  postgres:
    image: 'postgres:latest'
    ports:
      - "5432:5432"
    deploy:
      mode: global
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/